### ISSUE TITLE
规范太严格了，AMD使用module.exports直接说变量出错！

### ISSUE THREAD

**Issue by WuChu** [leeight/Baidu-FE-Code-Style#13]
规范太严格了，AMD使用module.exports直接说变量出错！

**Comment by chriswong** [comment]
你的 module 不是 factory 中的参数吧？或者你写的是 node？

**Comment by WuChu** [comment]
@chriswong 
基于构建工具[browserify](https://www.npmjs.com/package/grunt-browserify)开发的项目，module、exports、require基本都是预置函数或者变量了（也就算是node了），项目自动打包合并成factory形式，那么基本check每个js源文件都会报错了。

**Comment by chriswong** [comment]
fecs 又不知道你是会用 browserify 构建的代码，只能你通过 .fecsrc 告诉它了，现在默认已经设成 node 的 env，不会报的

**Comment by WuChu** [comment]
OK，Thks.
